<% director_uuid = 'cf2ca939-4344-4f17-9e6b-f6c7b69e26b5' %>
<% deployment_name = 'shipyard' %>
<% elastic_ip = '54.67.60.255' %>
<% tld = 'cloud.high.am' %>
<% num_nodes = 3 %>
---
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

releases:
 - name: shipyard
   version: latest

compilation:
  workers: 1
  network: cf-vpc
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.xlarge

update:
  canaries: 0
  canary_watch_time: 30000-240000
  update_watch_time:  30000-240000
  max_in_flight: <%= 1 + num_nodes %>
  serial: false

networks:
  - name: cf-vpc
    type: manual
    subnets:
    - cloud_properties:
        security_groups:
        - bosh-vpc-4ff33f2a
        - <%= deployment_name %>
        - ssh
        subnet: subnet-dc7e9b85
      gateway: 10.10.1.1
      range: 10.10.1.0/24
      reserved:
      - 10.10.1.2 - 10.10.1.20

  - name: default
    type: dynamic
    cloud_properties:
      security_groups:
        - bosh-vpc-4ff33f2a
        - <%= deployment_name %>
        - ssh

  - name: elastic
    type: vip
    cloud_properties: {}

resource_pools:
  - name: shipyard
    network: default
    size: 1
    stemcell:
      name: bosh-aws-xen-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m1.xlarge

  - name: nodes
    network: default
    size: <%= num_nodes %>
    stemcell:
      name: bosh-aws-xen-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      instance_type: m1.xlarge

jobs:
  - name: shipyard
    templates:
      - name: docker
      - name: shipyard_db_vol
      - name: shipyard_db
      - name: shipyard
    instances: 1
    resource_pool: shipyard
    persistent_disk: 65536
    networks:
      - name: cf-vpc
        default: [dns, gateway]
      - name: elastic
        static_ips:
          - <%= elastic_ip %>
    update:
      serial: true

  - name: node
    templates:
      - name: docker
      - name: register_engine
    instances: <%= num_nodes %>
    resource_pool: nodes
    networks:
      - name: cf-vpc
        default: [dns, gateway]
    properties:
      docker:
        tcp_address: 0.0.0.0

properties:
  shipyard:
    port: 8080
    host: 54.153.41.42
    scheme: http
